packages:
  - "packages/*"
allowBuilds:
  "@ast-grep/lang-php": set this to true or false
  "@parcel/watcher": set this to true or false
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - "@ai-sdk/anthropic@4.0.4"
